#ifndef CONFIG_H
#define CONFIG_H

#define NUM_CELLS 16

#define CELL_OVERVOLTAGE_MV 4200
#define CELL_OVERVOLTAGE_RECOVERY_MV 4100

#define CELL_UNDERVOLTAGE_MV 3000
#define CELL_UNDERVOLTAGE_RECOVERY_MV 3200

#define MAX_CHARGE_CURRENT_A 20
#define MAX_DISCHARGE_CURRENT_A 40

#define MAX_CELL_TEMP_C 60
#define MIN_CELL_TEMP_C 0

#define I2C_BQ76952_ADDR 0x10

#endif